__title__ = 'robotframework-netmiko'
__description__ = 'RobotFramework Library used to wrap Netmiko'
__version__ = '1.0.0'
__author__ = 'Mitchell Mahan'
__author_email__ = 'mitchm87@gmail.com'
__license__ = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
__url__ = 'https://github.com/mitchmahan/robotframework-netmiko'
